{
  "crons": [
    {
      "path": "/api/cron-sheet-publisher",
      "schedule": "0 */8 * * *"
    }
  ]
}
// Write bulkQueue.ts
const bq = [];
bq.push("import fs from 'fs';");
bq.push("import path from 'path';");
bq.push("import { fetchExistingPosts, uploadImageToWordPress, publishPostToWordPress, fetchWordPressCategories, autoDetermineCategory } from './wordpress';");
bq.push("import { generateSeoArticle, generateDalleImage } from './openai';");
bq.push("");
bq.push("export interface BulkQueueItem {");
bq.push("  id: string; keyword: string; scheduleDate?: string;");
bq.push("  status: 'pending' | 'processing' | 'completed' | 'failed';");
bq.push("  error?: string; postUrl?: string; title?: string;");
bq.push("  createdAt: string; completedAt?: string;");
bq.push("}");
bq.push("");
bq.push("export interface BulkQueueState {");
bq.push("  isRunning: boolean; total: number; completed: number; failed: number;");
bq.push("  currentItem?: string; items: BulkQueueItem[]; settings?: any;");
bq.push("}");
bq.push("");
bq.push("const QUEUE_FILE = path.join(process.cwd(), 'data', 'bulk_queue.json');");
bq.push("");
bq.push("function ensureDataDir() {");
bq.push("  const dir = path.join(process.cwd(), 'data');");
bq.push("  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });");
bq.push("}");
bq.push("");
bq.push("export function getBulkQueueState(): BulkQueueState {");
bq.push("  ensureDataDir();");
bq.push("  if (!fs.existsSync(QUEUE_FILE)) return { isRunning: false, total: 0, completed: 0, failed: 0, items: [] };");
bq.push("  try { const raw = fs.readFileSync(QUEUE_FILE, 'utf8'); return JSON.parse(raw); }");
bq.push("  catch { return { isRunning: false, total: 0, completed: 0, failed: 0, items: [] }; }");
bq.push("}");
bq.push("");
bq.push("export function saveBulkQueueState(state: BulkQueueState) {");
bq.push("  ensureDataDir();");
bq.push("  fs.writeFileSync(QUEUE_FILE, JSON.stringify(state, null, 2), 'utf8');");
bq.push("}");
bq.push("");
bq.push("let isWorkerActive = false;");
bq.push("");
bq.push("export async function startBackgroundBulkQueue(keywords: string[], intervalHours: number, settings: any): Promise<BulkQueueState> {");
bq.push("  const now = new Date();");
bq.push("  const newItems: BulkQueueItem[] = keywords.map((kw, i) => {");
bq.push("    let scheduleDate: string | undefined = undefined;");
bq.push("    if (intervalHours > 0) {");
bq.push("      const t = new Date(now.getTime() + i * intervalHours * 60 * 60 * 1000);");
bq.push("      scheduleDate = t.toISOString().replace(/\\.\\d{3}Z$/, '');");
bq.push("    }");
bq.push("    return { id: String(Date.now()) + '_' + i + '_' + Math.random().toString(36).slice(2, 6), keyword: kw, scheduleDate, status: 'pending' as const, createdAt: new Date().toISOString() };");
bq.push("  });");
bq.push("  const state: BulkQueueState = { isRunning: true, total: newItems.length, completed: 0, failed: 0, items: newItems, settings };");
bq.push("  saveBulkQueueState(state);");
bq.push("  if (!isWorkerActive) { runBackgroundWorker().catch(err => console.error('[BG Worker Error]:', err)); }");
bq.push("  return state;");
bq.push("}");
bq.push("");
bq.push("export async function stopBackgroundBulkQueue(): Promise<BulkQueueState> {");
bq.push("  const state = getBulkQueueState(); state.isRunning = false; state.currentItem = undefined;");
bq.push("  saveBulkQueueState(state); return state;");
bq.push("}");
bq.push("");
bq.push("async function runBackgroundWorker() {");
bq.push("  if (isWorkerActive) return; isWorkerActive = true;");
bq.push("  try {");
bq.push("    while (true) {");
bq.push("      const state = getBulkQueueState();");
bq.push("      if (!state.isRunning) break;");
bq.push("      const pendingItem = state.items.find(item => item.status === 'pending');");
bq.push("      if (!pendingItem) { state.isRunning = false; state.currentItem = undefined; saveBulkQueueState(state); break; }");
bq.push("      pendingItem.status = 'processing'; state.currentItem = pendingItem.keyword; saveBulkQueueState(state);");
bq.push("      console.log('[Background Worker] Processing: ' + pendingItem.keyword);");
bq.push("      try {");
bq.push("        const result = await processSingleBulkArticle(pendingItem.keyword, pendingItem.scheduleDate, state.settings);");
bq.push("        pendingItem.status = 'completed'; pendingItem.postUrl = result.postUrl; pendingItem.title = result.title;");
bq.push("        pendingItem.completedAt = new Date().toISOString(); state.completed += 1;");
bq.push("      } catch (procErr: any) {");
bq.push("        console.error('[BG Worker] Failed: ' + pendingItem.keyword, procErr.message);");
bq.push("        pendingItem.status = 'failed'; pendingItem.error = procErr.message;");
bq.push("        pendingItem.completedAt = new Date().toISOString(); state.failed += 1;");
bq.push("      }");
bq.push("      state.currentItem = undefined; saveBulkQueueState(state);");
bq.push("      await new Promise(resolve => setTimeout(resolve, 5000));");
bq.push("    }");
bq.push("  } finally { isWorkerActive = false; }");
bq.push("}");
bq.push("");
bq.push("async function processSingleBulkArticle(keyword: string, scheduleDate: string | undefined, settings: any = {}) {");
bq.push("  const trimmedKeyword = keyword.trim();");
bq.push("  const wpUrl = settings.wpUrl || process.env.WORDPRESS_URL || 'https://tgcenters.com';");
bq.push("  const wpUsername = settings.wpUsername || process.env.WORDPRESS_USERNAME || 'n8n-bot';");
bq.push("  const wpAppPassword = settings.wpAppPassword || process.env.WORDPRESS_APP_PASSWORD || 'RPbI TjbC Hb08 wC5E Ok0U Dtpo';");
bq.push("  const openaiApiKey = settings.openaiApiKey || process.env.OPENAI_API_KEY;");
bq.push("  const publishStatus = settings.publishStatus || (process.env.WORDPRESS_DEFAULT_STATUS as 'publish' | 'draft') || 'draft';");
bq.push("  if (!openaiApiKey) throw new Error('OpenAI API key missing');");
bq.push("  const [existingPosts, categories] = await Promise.all([fetchExistingPosts(wpUrl), fetchWordPressCategories(wpUrl, wpUsername, wpAppPassword)]);");
bq.push("  const article = await generateSeoArticle({ keyword: trimmedKeyword, existingPosts, categories, apiKey: openaiApiKey });");
bq.push("  const [featuredImageUrl, inArticleImageUrl] = await Promise.all([");
bq.push("    generateDalleImage({ prompt: article.featuredImagePrompt, aspect: '1792x1024', apiKey: openaiApiKey }),");
bq.push("    generateDalleImage({ prompt: article.inArticleImagePrompt, aspect: '1024x1024', apiKey: openaiApiKey }),");
bq.push("  ]);");
bq.push("  const slug = article.slug || trimmedKeyword.toLowerCase().replace(/[^a-z0-9]+/g, '-');");
bq.push("  let featuredMedia = { id: 0, sourceUrl: featuredImageUrl };");
bq.push("  let inArticleMedia = { id: 0, sourceUrl: inArticleImageUrl };");
bq.push("  try {");
bq.push("    const [featRes, inArtRes] = await Promise.all([");
bq.push("      uploadImageToWordPress({ imageUrl: featuredImageUrl, filename: slug + '-featured.jpg', title: article.title + ' - Featured', altText: trimmedKeyword, wpUrl, username: wpUsername, appPassword: wpAppPassword }).catch(() => ({ id: 0, sourceUrl: featuredImageUrl })),");
bq.push("      uploadImageToWordPress({ imageUrl: inArticleImageUrl, filename: slug + '-diagram.jpg', title: article.title + ' - Diagram', altText: trimmedKeyword, wpUrl, username: wpUsername, appPassword: wpAppPassword }).catch(() => ({ id: 0, sourceUrl: inArticleImageUrl })),");
bq.push("    ]);");
bq.push("    if (featRes && featRes.sourceUrl) featuredMedia = featRes;");
bq.push("    if (inArtRes && inArtRes.sourceUrl) inArticleMedia = inArtRes;");
bq.push("  } catch (err: any) { console.warn('Image upload fallback:', err.message); }");
bq.push("  const imgCls = inArticleMedia.id ? 'wp-image-' + inArticleMedia.id + ' ' : '';");
bq.push("  const inArticleImageHtml = '<figure class=\"wp-block-image size-large my-6\"><img src=\"' + inArticleMedia.sourceUrl + '\" alt=\"' + trimmedKeyword + '\" class=\"' + imgCls + 'rounded-xl shadow-lg w-full\" /><figcaption>' + trimmedKeyword + '</figcaption></figure>';");
bq.push("  let finalContent = article.contentHtml;");
bq.push("  if (finalContent.includes('<!-- IN_ARTICLE_IMAGE_HERE -->')) { finalContent = finalContent.replace('<!-- IN_ARTICLE_IMAGE_HERE -->', inArticleImageHtml); }");
bq.push("  else {");
bq.push("    const h2s = [...finalContent.matchAll(/<\\/h2>/g)];");
bq.push("    if (h2s.length >= 2) { const m = h2s[Math.floor(h2s.length / 2)]; const idx = m.index! + 5; finalContent = finalContent.slice(0, idx) + inArticleImageHtml + finalContent.slice(idx); }");
bq.push("    else { const mp = Math.floor(finalContent.length / 2); const np = finalContent.indexOf('</p>', mp); if (np !== -1) { finalContent = finalContent.slice(0, np + 4) + inArticleImageHtml + finalContent.slice(np + 4); } else { finalContent = finalContent + inArticleImageHtml; } }");
bq.push("  }");
bq.push("  const categoryId = article.category?.id || autoDetermineCategory(trimmedKeyword, article.title).id;");
bq.push("  const publishedPost = await publishPostToWordPress({ title: article.title, slug: article.slug, contentHtml: finalContent, metaDescription: article.metaDescription, focusKeyword: article.focusKeyword, featuredMediaId: featuredMedia.id, categoryId, status: scheduleDate ? 'future' : publishStatus, date: scheduleDate, wpUrl, username: wpUsername, appPassword: wpAppPassword });");
bq.push("  return { postUrl: publishedPost.link, title: article.title };");
bq.push("}");
fs.writeFileSync('src/lib/bulkQueue.ts', bq.join('\n'), 'utf8');
console.log('OK: bulkQueue.ts');

// Start route
const sr = [];
sr.push("import { NextRequest, NextResponse } from 'next/server';");
sr.push("import { startBackgroundBulkQueue } from '@/lib/bulkQueue';");
sr.push("export const maxDuration = 300;");
sr.push("export async function POST(req: NextRequest) {");
sr.push("  try {");
sr.push("    const body = await req.json();");
sr.push("    const { keywords, intervalHours = 8, settings = {} } = body;");
sr.push("    if (!Array.isArray(keywords) || keywords.length === 0) return NextResponse.json({ error: 'Keywords array required' }, { status: 400 });");
sr.push("    const clean = keywords.map((k: string) => k.trim()).filter(Boolean);");
sr.push("    if (clean.length === 0) return NextResponse.json({ error: 'No valid keywords' }, { status: 400 });");
sr.push("    console.log('[Bulk Queue] Starting for ' + clean.length + ' keywords...');");
sr.push("    const state = await startBackgroundBulkQueue(clean, intervalHours, settings);");
sr.push("    return NextResponse.json({ success: true, message: 'Background queue started. Safe to close browser.', total: state.total, items: state.items.map(i => ({ keyword: i.keyword, scheduleDate: i.scheduleDate, status: i.status })) });");
sr.push("  } catch (error: any) {");
sr.push("    console.error('Error starting bulk queue:', error);");
sr.push("    return NextResponse.json({ error: error.message || 'Failed' }, { status: 500 });");
sr.push("  }");
sr.push("}");
fs.writeFileSync('src/app/api/bulk-queue/start/route.ts', sr.join('\n'), 'utf8');
console.log('OK: start/route.ts');

// Status route
const st = [];
st.push("import { NextResponse } from 'next/server';");
st.push("import { getBulkQueueState } from '@/lib/bulkQueue';");
st.push("export const dynamic = 'force-dynamic';");
st.push("export async function GET() {");
st.push("  try {");
st.push("    const state = getBulkQueueState();");
st.push("    return NextResponse.json({ isRunning: state.isRunning, total: state.total, completed: state.completed, failed: state.failed, currentItem: state.currentItem, items: state.items.map(i => ({ id: i.id, keyword: i.keyword, scheduleDate: i.scheduleDate, status: i.status, error: i.error, postUrl: i.postUrl, title: i.title, completedAt: i.completedAt })) });");
st.push("  } catch (error: any) { return NextResponse.json({ error: error.message }, { status: 500 }); }");
st.push("}");
fs.writeFileSync('src/app/api/bulk-queue/status/route.ts', st.join('\n'), 'utf8');
console.log('OK: status/route.ts');

// Stop route
const sp = [];
sp.push("import { NextResponse } from 'next/server';");
sp.push("import { stopBackgroundBulkQueue } from '@/lib/bulkQueue';");
sp.push("export async function POST() {");
sp.push("  try {");
sp.push("    const state = await stopBackgroundBulkQueue();");
sp.push("    return NextResponse.json({ success: true, message: 'Queue stopped', completed: state.completed, failed: state.failed, remaining: state.items.filter(i => i.status === 'pending').length });");
sp.push("  } catch (error: any) { return NextResponse.json({ error: error.message }, { status: 500 }); }");
sp.push("}");
fs.writeFileSync('src/app/api/bulk-queue/stop/route.ts', sp.join('\n'), 'utf8');
console.log('OK: stop/route.ts');

console.log('ALL DONE');
